### ISSUE TITLE
There may be a mistake   [I'm not sure]

### ISSUE THREAD

**Issue by yizhangliu** [opendilab/GoBigger-Challenge-2021#5]
Thanks for your work.  There may be a mistake in function  _to_raw_action(act: int).

        if direction == 0:
            x, y = 0, 1
        elif direction == 1:
            x, y = 0, -1

Maybe it should be:

        if direction == 0:
            x, y = 0, -1
        elif direction == 1:
            x, y = 0, 1

**Comment by mingzhang96** [comment]
Thanks for your question! 

I don't think it is a mistake. The correspondence between `direction` and `(x, y)` is not important, you just need to ensure one-to-one correspondence. Hope this helps!
